spring:
  # .env import
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:mariadb://localhost:3306/snackscan?allowPublicKeyRetrieval=true
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MariaDBDialect
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        highlight_sql: true
        dialect: org.hibernate.dialect.MariaDBDialect
        hbm2ddl:
          auto: update
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true
        show_sql: true

logging:
  level:
    # 애플리케이션 로거 레벨 설정
    com.snackscan: info
    # 프레임워크 로거 레벨 설정
    org.hibernate.SQL: debug
    org.hibernate.type: trace
    org.springframework.core.env: debug
    org.springframework.web: info
    org.springframework.security: debug
  # 로그 패턴 설정 (콘솔 출력만)
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"